services:
#  rabbitmq:
#    image: rabbitmq
#    container_name: 'rabbitmq'
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - C:\Users\user\Desktop\dockerImagesData\rabbitmq\data:/var/lib/rabbitmq/
#      - C:\Users\user\Desktop\dockerImagesData\rabbitmq\log:/var/log/rabbitmq

  redis:
    image: "redis"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "9201:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
